<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8RNOGRT" failures="1" tests="6" name="practice.homeTest.InvoiceTest" time="78.675" errors="0" timestamp="2024-05-16T12:26:35 IST" skipped="5">
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="13.127">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="12.741">
    <failure message="expected [ ] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [ ] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at practice.homeTest.InvoiceTest.createInvoiceTest(InvoiceTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="12.387">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="12.683">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="14.307">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
  <testcase classname="practice.homeTest.InvoiceTest" name="createInvoiceTest" time="13.430">
    <skipped/>
  </testcase> <!-- createInvoiceTest -->
  <system-out/>
</testsuite> <!-- practice.homeTest.InvoiceTest -->
